version: '3'
services:
  frontend:
    build:
      context: ./frontend  # Point to the frontend folder
      dockerfile: Dockerfile  # Use the frontend Dockerfile
    ports:
      - "80:80"  # Expose frontend on port 80
    depends_on:
      - backend

  backend:
    build:
      context: ./backend  # Point to the backend folder
      dockerfile: Dockerfile  # Use the backend Dockerfile
    ports:
      - "8080:8080"  # Expose backend on port 8080
    environment:
      - SPRING_PROFILES_ACTIVE=prod  # Specify Spring profile if needed
